// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjoCOA73RU2EqlbOYf3X3-UYhImGvrSBU',
    appId: '1:395967347667:web:419983afc9521ccace4d26',
    messagingSenderId: '395967347667',
    projectId: 'fir-firebase-4110f',
    authDomain: 'fir-firebase-4110f.firebaseapp.com',
    databaseURL: 'https://fir-firebase-4110f.firebaseio.com',
    storageBucket: 'fir-firebase-4110f.appspot.com',
    measurementId: 'G-T02NK02MK7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArqYWg7prZT97UiziP1JeOxUyDN7RLDe4',
    appId: '1:395967347667:android:99a62e6f0e19dedfce4d26',
    messagingSenderId: '395967347667',
    projectId: 'fir-firebase-4110f',
    databaseURL: 'https://fir-firebase-4110f.firebaseio.com',
    storageBucket: 'fir-firebase-4110f.appspot.com',
  );
}
